export  const specialties = [
    "Cardiology",
    "Dermatology",
    "Pediatrics",
    "Orthopedics",
    "Neurology",
    "Psychiatry",
    "Gynecology",
    "Oncology",
    "Gastroenterology",
    "Endocrinology",
    "Pulmonology",
    "Urology",
    "Rheumatology",
    "Ophthalmology",
    "Anesthesiology"
  ];
  export const doctors = [
    { id: 1, name: "Dr. Smith", specialty: "Cardiology", fees: "$150", hospital: "City Hospital", timing: "6:00 AM - 8:00 AM", gender: "Male" },
    { id: 2, name: "Dr. Johnson", specialty: "Dermatology", fees: "$120", hospital: "Greenwood Clinic", timing: "7:00 AM - 9:00 AM", gender: "Female" },
    { id: 3, name: "Dr. Williams", specialty: "Pediatrics", fees: "$100", hospital: "Children's Hospital", timing: "6:30 AM - 8:30 AM", gender: "Male" },
    { id: 4, name: "Dr. Brown", specialty: "Orthopedics", fees: "$180", hospital: "OrthoCare Center", timing: "8:00 AM - 10:00 AM", gender: "Male" },
    { id: 5, name: "Dr. Jones", specialty: "Gynecology", fees: "$160", hospital: "Women's Health Center", timing: "7:15 AM - 9:15 AM", gender: "Female" },
    { id: 6, name: "Dr. Garcia", specialty: "Neurology", fees: "$200", hospital: "NeuroHealth Institute", timing: "8:30 AM - 10:30 AM", gender: "Female" },
    { id: 7, name: "Dr. Martinez", specialty: "Ophthalmology", fees: "$130", hospital: "EyeCare Clinic", timing: "6:45 AM - 8:45 AM", gender: "Male" },
    { id: 8, name: "Dr. Rodriguez", specialty: "General Practice", fees: "$90", hospital: "Main Street Medical", timing: "7:00 AM - 9:00 AM", gender: "Male" },
    { id: 9, name: "Dr. Lee", specialty: "Psychiatry", fees: "$170", hospital: "Mental Wellness Center", timing: "8:00 AM - 10:00 AM", gender: "Female" },
    { id: 10, name: "Dr. Gonzalez", specialty: "Endocrinology", fees: "$150", hospital: "Endocrine Clinic", timing: "6:50 AM - 8:50 AM", gender: "Male" },
    { id: 11, name: "Dr. Perez", specialty: "Allergy & Immunology", fees: "$140", hospital: "Allergy Institute", timing: "7:45 AM - 9:45 AM", gender: "Female" },
    { id: 12, name: "Dr. Wilson", specialty: "Gastroenterology", fees: "$160", hospital: "Gastro Center", timing: "8:10 AM - 10:10 AM", gender: "Male" },
    { id: 13, name: "Dr. Anderson", specialty: "Urology", fees: "$180", hospital: "Urology Clinic", timing: "8:20 AM - 10:20 AM", gender: "Male" },
    { id: 14, name: "Dr. Thomas", specialty: "Oncology", fees: "$220", hospital: "Cancer Care Center", timing: "9:00 AM - 11:00 AM", gender: "Female" },
    { id: 15, name: "Dr. Taylor", specialty: "Anesthesiology", fees: "$190", hospital: "Surgery Center", timing: "7:30 AM - 9:30 AM", gender: "Male" },
    { id: 16, name: "Dr. Moore", specialty: "Rheumatology", fees: "$150", hospital: "Rheumatology Institute", timing: "7:10 AM - 9:10 AM", gender: "Female" },
    { id: 17, name: "Dr. Jackson", specialty: "Internal Medicine", fees: "$110", hospital: "Internal Medicine Clinic", timing: "8:35 AM - 10:35 AM", gender: "Male" },
    { id: 18, name: "Dr. White", specialty: "Family Medicine", fees: "$95", hospital: "Family Health Center", timing: "6:55 AM - 8:55 AM", gender: "Female" },
    { id: 19, name: "Dr. Harris", specialty: "Plastic Surgery", fees: "$250", hospital: "Aesthetic Clinic", timing: "7:50 AM - 9:50 AM", gender: "Male" },
    { id: 20, name: "Dr. Martin", specialty: "Nephrology", fees: "$175", hospital: "Kidney Care Center", timing: "8:40 AM - 10:40 AM", gender: "Female" },
    { id: 21, name: "Dr. Thompson", specialty: "Otolaryngology", fees: "$160", hospital: "ENT Clinic", timing: "6:40 AM - 8:40 AM", gender: "Male" },
    { id: 22, name: "Dr. Foster", specialty: "Cardiothoracic Surgery", fees: "$300", hospital: "Heart Center", timing: "9:00 AM - 11:00 AM", gender: "Female" }
];
