export  const doctors = [
    { name: "Dr. Smith", specialty: "Cardiology", price: 150 },
    { name: "Dr. Johnson", specialty: "Dermatology", price: 120 },
    { name: "Dr. Williams", specialty: "Pediatrics", price: 100 },
    { name: "Dr. Brown", specialty: "Orthopedics", price: 180 },
    { name: "Dr. Jones", specialty: "Gynecology", price: 160 },
    { name: "Dr. Garcia", specialty: "Neurology", price: 200 },
    { name: "Dr. Martinez", specialty: "Ophthalmology", price: 130 },
    { name: "Dr. Rodriguez", specialty: "General Practice", price: 90 },
    { name: "Dr. Lee", specialty: "Psychiatry", price: 170 },
    { name: "Dr. Gonzalez", specialty: "Endocrinology", price: 150 },
    { name: "Dr. Perez", specialty: "Allergy & Immunology", price: 140 },
    { name: "Dr. Wilson", specialty: "Gastroenterology", price: 160 },
    { name: "Dr. Anderson", specialty: "Urology", price: 180 },
    { name: "Dr. Thomas", specialty: "Oncology", price: 220 },
    { name: "Dr. Taylor", specialty: "Anesthesiology", price: 190 },
    { name: "Dr. Moore", specialty: "Rheumatology", price: 150 },
    { name: "Dr. Jackson", specialty: "Internal Medicine", price: 110 },
    { name: "Dr. White", specialty: "Family Medicine", price: 95 },
    { name: "Dr. Harris", specialty: "Plastic Surgery", price: 250 },
    { name: "Dr. Martin", specialty: "Nephrology", price: 175 },
    { name: "Dr. Thompson", specialty: "Otolaryngology", price: 160 },
    { name: "Dr. Garcia", specialty: "Radiology", price: 140 },
    { name: "Dr. Martinez", specialty: "Sports Medicine", price: 130 },
    { name: "Dr. Robinson", specialty: "Podiatry", price: 120 },
    { name: "Dr. Clark", specialty: "Vascular Surgery", price: 210 },
    { name: "Dr. Rodriguez", specialty: "Emergency Medicine", price: 200 }
  ];
  